tools:
    php_cpd: true
    php_pdepend: true
    php_loc: true
    php_code_coverage: true
    php_mess_detector: true
    php_code_sniffer:
        enabled: true
        command: phpcs
        config:
            standard: PSR2
    php_analyzer: true
