language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

install:
  - composer install --dev

before_script:
  - composer update --prefer-source $PREFER_LOWEST 

script:
  - phpunit
